### ISSUE TITLE
Might break SSR

### ISSUE THREAD

**Issue by rileyjshaw** [Khan/react-balance-text#1]
We [`import balanceText`](https://github.com/Khan/react-balance-text/blob/ea45924c86431906cad40dc05739d331658a758f/src/index.js#L2) right off the bat, which references `window` and `document`. I _think_ this causes problems for SSR, but @xymostech @jeresig feel free to correct me!

Two solutions that I can think of:

- (my favorite) send a patch to `balance-text` to make it more SSR friendly
- render a plain `div`, then pull in `balanceText` on `componentDidMount`

I'm not sure if we have internal whitelists for globals like this, but since this is OSS it's worth discussion :)

**Comment by BrianGenisio** [comment]
I like the first option.  Especially since I am still finalizing the PR that will get merged to (`master`)[https://github.com/adobe-webplatform/balance-text/pull/95]:   Seems like we should just have a guard clause in the public functions that returns if `window` is not defined.  And then the react component would just render the innards without balancing.  Would that be sufficient?

**Comment by jeresig** [comment]
Inherently `window` and `document` aren't a problem, they're both implemented in SSR-land (we also support rendering things like Backbone Views and Handlebars templates). That being said some of the things happening in balance-text may be a problem. For example, I doubt `isJustified` will work as expected, nor will the logic around `hasTextWrap` (especially since it's attempting to create a browser-centric solution).

**Comment by rileyjshaw** [comment]
On SSR'd projects I've worked on outside of KA, `window` and `document` haven't been so forgiving - so I've seen this type of check:

```
if (typeof window === 'undefined' || typeof document === 'undefined') {
```

@jeresig if we implement `window` and `document` in SSR-land, is there a better "is server" check you can recommend?

@BrianGenisio I guess early-returning `undefined` is technically a breaking change? If this was already failing on servers, it seems totally reasonable.

**Comment by matchu** [comment]
Wait, where's the immediate call to `window` and `document`? We import [our custom balance-text.js](https://github.com/Khan/balance-text/blob/native/balancetext.js), right? It looks safe to me; it only contains function definitions.

**Comment by jeresig** [comment]
@rileyjshaw I think, generally, the better solution is to follow option #2 that you proposed above, especially if browser-specific features are needed. Maybe an alternative could be to render it but using the `text-wrap` property and then, on `componentDidMount` update the result to use the `<span>`s and `<br>`s, but only if `text-wrap` doesn't work.

**Comment by BrianGenisio** [comment]
@matchu Although we do (currently) import our custom balance-text.js, that change is being rolled in to the upstream repo as well.

@rileyjshaw Yeah, it would be a breaking change.  Do we know if it is a problem with SSR?  Or are we hypothesizing?

@jeresig If we go with #2, how do I detect whether it (`text-wrap`) worked or not?  Also, how would I detect whether it is being Server-Side-Rendered to make a decision either way?  

If the solution is specific to the way we do SSR, then I think we should do #2 to avoid polluting the vanilla balance-text project with our opinions.

**Comment by matchu** [comment]
Wait, so, I'm still confused where the problem lies. It looks like the
import itself doesn't dereference any globals, and we don't make any
balanceText calls until componentDidMount and componentDidUpdate, which
aren't called during server-side rendering.

I hope I'm not slowing down a conversation where everyone else is on the
same page, but now I'm curious is all ^_^` Exactly what codepath causes
problems during SSR, and how?

**Comment by BrianGenisio** [comment]
@matchu I'm not sure if it is an issue.  For the record, we are currently using the original jQuery version of balance-text in a [component in production](https://github.com/Khan/webapp/blob/master/javascript/donate-package/hopper.jsx).  If this were a problem, (unless I'm misunderstanding), we'd be seeing it here as well?

**Comment by rileyjshaw** [comment]
@matchu I'm confused too. I set up a test project with [Gatsby](https://github.com/gatsbyjs/gatsby), and `var _balanceText2 = require('balance-text');` seems to actually _call_ the factory during the build step. Doesn't seem like it should, so I'm looking into their build stack.

Specifically, [this line in balance-text](https://github.com/Khan/balance-text/blob/6ce6f310459da4430f2a7083056385c77a5e3632/balancetext.js#L178) trips things up. But again, I'm not sure why this would be hit before `componentDidMount`, etc.

I'm fine to close this since it doesn't seem like a KA problem, but keeping it open in case there's remaining discussion around option #2.

**Comment by rileyjshaw** [comment]
@matchu the UMD loader calls `factory` right away, so [this line in balance-text](https://github.com/Khan/balance-text/blob/6ce6f310459da4430f2a7083056385c77a5e3632/balancetext.js#L178) trips things up.

**Comment by BrianGenisio** [comment]
@rileyjshaw Ah.  Ok.  That line only exists to make sure `hasTextWrap` is checked. I'll just make `hasTextWrap` into a function instead (in the balance-text repo).  Would that be sufficient to fix your problem?

**Comment by rileyjshaw** [comment]
👍

**Comment by BrianGenisio** [comment]
I've [added the change](https://github.com/Khan/balance-text/commit/2191a197f5d1da44e6ba088542ebf21d75d703ef) to the (hopefully soon) pending re-write of the balance-text module.  We good to close this @rileyjshaw?
